steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build' ,'-f', '/workspace/devops/docker/dockerfile-fakeami' ,'-t', 'gcr.io/$PROJECT_ID/fakeapi:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/fakeapi:latest', '.' ]
images:
- 'gcr.io/$PROJECT_ID/fakeapi:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/fakeapi:latest'
