/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TwilioRouteImport } from './routes/twilio'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MockIndexRouteImport } from './routes/mock/index'
import { Route as MockNameRouteImport } from './routes/mock/$name'

const TwilioRoute = TwilioRouteImport.update({
  id: '/twilio',
  path: '/twilio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MockIndexRoute = MockIndexRouteImport.update({
  id: '/mock/',
  path: '/mock/',
  getParentRoute: () => rootRouteImport,
} as any)
const MockNameRoute = MockNameRouteImport.update({
  id: '/mock/$name',
  path: '/mock/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/twilio': typeof TwilioRoute
  '/mock/$name': typeof MockNameRoute
  '/mock/': typeof MockIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/twilio': typeof TwilioRoute
  '/mock/$name': typeof MockNameRoute
  '/mock': typeof MockIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/twilio': typeof TwilioRoute
  '/mock/$name': typeof MockNameRoute
  '/mock/': typeof MockIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/twilio' | '/mock/$name' | '/mock/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/twilio' | '/mock/$name' | '/mock'
  id: '__root__' | '/' | '/twilio' | '/mock/$name' | '/mock/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TwilioRoute: typeof TwilioRoute
  MockNameRoute: typeof MockNameRoute
  MockIndexRoute: typeof MockIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/twilio': {
      id: '/twilio'
      path: '/twilio'
      fullPath: '/twilio'
      preLoaderRoute: typeof TwilioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock/': {
      id: '/mock/'
      path: '/mock'
      fullPath: '/mock/'
      preLoaderRoute: typeof MockIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock/$name': {
      id: '/mock/$name'
      path: '/mock/$name'
      fullPath: '/mock/$name'
      preLoaderRoute: typeof MockNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TwilioRoute: TwilioRoute,
  MockNameRoute: MockNameRoute,
  MockIndexRoute: MockIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
