import { createRouter } from '@tanstack/react-router'

// Generated by @tanstack/router-plugin — do not edit manually.
import { routeTree } from './routeTree.gen'

// Derive basepath from Vite's BASE_URL so it's '/ui' in both dev and prod.
const basepath = import.meta.env.BASE_URL.replace(/\/$/, '')

export const router = createRouter({ routeTree, basepath })

// Register router type for useRouter(), useMatch(), etc.
declare module '@tanstack/react-router' {
    interface Register {
        router: typeof router
    }
}
